services:
  app:
    container_name: bookmanage-app
    build:
      context: ../
      dockerfile: app/Dockerfile.dev
    working_dir: /code/app
    entrypoint: ["/code/docker/entrypoint.sh"]
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=app_user
      - DB_PASSWORD=app_password
      - DB_NAME=app_db
    volumes:
      - ../:/code
      - /code/app/node_modules
    ports:
      - "3000:3000"
  db:
    image: postgres:15
    container_name: bookmanage-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_USER=app_user
      - POSTGRES_DB=app_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data: 